import { AbstractSchema } from "./abstract"
import { Field, ObjectType, ID, Float, GraphQLISODateTime } from "@nestjs/graphql"
import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose"
import { Types } from "mongoose"
import { PoopSchema, PoopSchemaClass } from "./poop.schema"
import { GraphQLTypePetStatus, PetStatus } from "../enums"
import { UserSchema } from "./user.schema"
import { PetSchema } from "./pet.schema"

@Schema({ timestamps: true, collection: "owned-pets" })
@ObjectType({
    description:
        "Represents a pet owned by a user in the game world. A pet has type, stats, growth status, and can produce resources or poops over time.",
})
export class OwnedPetSchema extends AbstractSchema {
    // user who owns the pet
    @Field(() => ID, {
        description: "The unique identifier of the user who owns this pet.",
    })
    @Prop({ type: Types.ObjectId, ref: UserSchema.name, required: true })
        user: UserSchema | Types.ObjectId

    // pet that is owned by the user
    // @Field(() => ID, {
    //     description: "The unique identifier of the pet that is owned by the user.",
    // })
    // @Prop({ type: Types.ObjectId, ref: PetSchema.name, required: true })
    //     pet: PetSchema | Types.ObjectId

    @Field(() => ID, {
        description: "Reference to the pet species or type (defines its base stats and visual appearance).",
    })
    @Prop({ type: Types.ObjectId, ref: PetSchema.name, required: true })
        type: PetSchema | Types.ObjectId

    @Field(() => String, {
        description: "The given name of the pet as chosen by the user.",
    })
    @Prop({ type: String, required: true })
        name: string

    @Field(() => Float, {
        description: "The pet's current happiness level (0–100 scale).",
    })
    @Prop({ type: Number, required: true, default: 100 })
        happiness: number

    @Field(() => GraphQLISODateTime, {
        description: "The timestamp of the last happiness update.",
    })
    @Prop({ type: Date, required: true, default: () => new Date() })
        lastUpdateHappiness: Date

    @Field(() => Float, {
        description: "The pet's current hunger level (0-100 scale).",
    })
    @Prop({ type: Number, required: true, default: 100 })
        hunger: number

    @Field(() => GraphQLISODateTime, {
        description: "The timestamp of the last hunger update.",
    })
    @Prop({ type: Date, required: true, default: () => new Date() })
        lastUpdateHunger: Date

    @Field(() => Float, {
        description: "The pet's cleanliness level (0–100 scale).",
    })
    @Prop({ type: Number, required: true, default: 100 })
        cleanliness: number

    @Field(() => GraphQLISODateTime, {
        description: "The timestamp of the last cleanliness update.",
    })
    @Prop({ type: Date, required: true, default: () => new Date() })
        lastUpdateCleanliness: Date

    @Field(() => GraphQLTypePetStatus, {
        description: "The current activity status of the pet.",
    })
    @Prop({
        type: String,
        enum: PetStatus,
        default: PetStatus.Active,
    })
        status: PetStatus

    @Field(() => Boolean, {
        description: "Whether the pet has reached adulthood and unlocked advanced interactions.",
    })
    @Prop({ type: Boolean, required: true, default: false })
        isAdult: boolean

    @Field(() => Float, {
        description: "The current token income rate generated by this pet.",
    })
    @Prop({ type: Number, required: true, default: 0 })
        tokenIncome: number

    @Field(() => Float, {
        description: "Total accumulated token income earned by this pet over its lifetime.",
    })
    @Prop({ type: Number, required: true, default: 0 })
        totalIncome: number

    @Field(() => [PoopSchema], {
        description: "A list of poop objects created by this pet.",
        nullable: true,
    })
    @Prop({ type: [PoopSchemaClass], required: true, default: [] })
        poops: Array<PoopSchema>

    @Field(() => GraphQLISODateTime, {
        description: "The last time the pet claimed its token or resource rewards.",
    })
    @Prop({ type: Date, required: true, default: () => new Date() })
        lastClaim: Date
}

export const OwnedPetSchemaClass = SchemaFactory.createForClass(OwnedPetSchema)
